### ISSUE TITLE
snplist2 - list <c> elements, refinement

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/Markup-Sanskrit-Names-of-Plants#13]
The usage will be:

```
python snplist2.py data/snp04.txt data/snp04_list2.txt
```

Use the Counter module:

```
from collections import Counter
...
c = Counter() # initialize empty counter
```

Find the list `l` of tags, as in snplist1.  Then loop through `l` , making the modifications as in snplist1,
but instead of writing out the modified element,  add it to your counter:

```
for x in l:
  x = re.sub....
  ...
  c.update([x])  # [x] is a list literal.  Otherwise, counter will use the letters of x 
```

Finally, write out c.  'c' is like a dict.   Get its keys,  sort its keys and then iterate over the sorted keys
For each key `k`, write out the value of c at `k`, and `k`, formatted so that the keys "line-up" in the output file.

If you get stuck, write message here and I'll comment.

**Comment by beenooyadav** [comment]
@funderburkjim 
snp04_list2.txt and snplist2.py done

**Comment by funderburkjim** [comment]
@beenooyadav  Basically this is fine.  I had intended that you sort by the keys (2nd column) in snp04_list2.txt,
but your sort on the values (count, 1st column) is interesting as well.  So, we'll call it done.
