### ISSUE TITLE
snp05 - removing markup of non-botanical words

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/Markup-Sanskrit-Names-of-Plants#14]
I think most of the adjustments we need to make can be done using that subset of snp04_list2.txt consisting of just one word.   
## What I did in preparation for your snp05.py

Using a text editor (EMACS, in my case), I edited snp04_list2 and did the following:
- select the lines that DID NOT contain the regex pattern (in Python syntax):

```
r'<c>.* '    
i.e., <c> + {zero-or-more characters} + {space character}
```

  This subset was saved into a temporary file (temp)
- edit temp,  remove the counts, save
- edit temp, select the lines that contain a period, save result as data/snp04_one_period.txt.  Will use this in snp06
- edit temp, select the lines that do NOT contain a period; save result as a second temporary file, temp1
- delete temp
- open two new files: snp04_one_noperiod_nobot.txt and snp04_one_noperiod_bot.txt.
- edit temp1
  - Look at each line, and search snp04.txt for these cases.  Make a subjective determination 
    of whether the word is a botanical designation or not
  - If line in temp1 is botanical, move it to snp04_one_noperiod_bot.txt  
  - if line in temp1 is non-botanical, move it to snp04_one_noperiod_nobot.txt 
- save snp04_one_noperiod_nobot.txt and snp04_one_noperiod_bot.txt.
- delete temp1

We will probably not make further use of snp04_one_noperiod_bot.txt, except maybe to identify a couple
of potential typographical errors.
## What you will do in snp05

snp05.py will use snp04_one_noperiod_nobot.txt .

Here's the calling sequence for snp05.py:

```
python snp05.py data/snp04.txt data/snp04_one_noperiod_nobot.txt snp05.txt
```
- First, sync your local version so you'll have these new files.
- Read snp04_one_noperiod_nobot into a dict  (call tht dict nobot).
  The keys of nobot will be the lines of the file, after stripping the line-ending character(s))
  e.g.

```
nobot = {}
f = (open snp04_one_noperiod_nobot.txt)
for l in f:
  l = l.rstrip('\r\n')
  nobot[l] = True
```
- Now read snp04.txt line by line

```
  for l in f: 
  Use re.findall to get the instances caps of the form <c>..</c>  in the line
  caps = re.findall(r'...',l)  # could be the empty list
  for x in caps:
   if x in nobot:   
     # x has form <c>w</c>. Use some means (e.g., re.search) to find w
     # then
      l = re.sub(x,w,l)
```
- write out the (possibly modified) l  to snp05

That's it.  Check your snp05.txt and compare to snp04.txt to be sure that you've unmarked KB, etc , and have made no other changes.

When you're done, sync to github and enter a message here.
As usual, if you get stuck,  post a question here.
Good luck!

**Comment by drdhaval2785** [comment]
@funderburkjim wish i had learnt python with you..

**Comment by funderburkjim** [comment]
@beenooyadav  P.S.  Another way you could check snp05.txt is to run snp_list2.py on snp05.txt and compare the snp05_list2.txt file to see if the desired changes have been made.

**Comment by funderburkjim** [comment]
@drdhaval2785   How do you like python relative to your favored php?

**Comment by drdhaval2785** [comment]
@funderburkjim I have not learnt enough python to compare both. But yes, I would love to learn python.
From whatever I laid my hands on, I think python 2 is better than python 3 in term of syntax.
And both seem to be somewhat different languages.
So my first question would be which one to learn?

**Comment by beenooyadav** [comment]
@funderburkjim 
snp05.py and snp05.txt done

**Comment by funderburkjim** [comment]
@beenooyadav   snp05 is not quite right.  You can see the problem if you compare line 97 from snp04.txt and
snp05.txt:

```
snp04.txt
<P>b) <c>KB</c> 1, p. 528-529: <c>COMMIPHORA AGALLOCHA ENGL.</c> = <c>BALSA-
snp05.txt
<P>b) KB 1, p. 528-529: COMMIPHORA AGALLOCHA ENGL. = <c>BALSA-
```

Do you see the problem?  Although it is correct to remove the markup around 'KB', it is NOT correct to
remove the markup around 'COMMIPHORA AGALLOCHA ENGL.' .

The problem occurs at line 29 of snp05.py:

```
            l=re.sub(r'<c>(.*?)</c>',r'\1',l)
```

Here's the whole loop:

```
for l in f:
    #find c-tags from snp04.txt
    caps=re.findall(r'<c>.*?</c>',l)
    for x in caps:
        #if x in caps
        if x in nobot:
            #if x is in dict(nobot) remove c-tags
            # You are removing the tags for ANY substring of l matching <c>(.*?)</c>, but what you
            # want to replace is just when <c>(.*?)</c> is x.
            # The problem you have to solve is, this.  We know x has the form <c>(.*?)</c>.  So if we match
            # x, then the capture group will give us the text part of x
            m = re.search(r'<c>(.*?)</c>,x)
            if not m:   # this should never happen
              print "ERROR"
              exit(1)
            w = ...  # w is the text inside of x
             l = re.sub(x,w,l)  
             # another way to get 'w' would be to remove <c> and </c> from x, such as with re.sub or
             #  with x.replace(....)
            #l=re.sub(r'<c>(.*?)</c>',r'\1',l)   wrong

    w.write(l)
```

So, you'll need to make a change to your program as indicated, and remake snp05.txt
When you've done that check that line 97 in snp05.txt is right, and check a few others.
Then sync and provide a message here so I'll know to look.

By the way, I think the next step (snp06) is probably the last one you'll have time to complete.

**Comment by beenooyadav** [comment]
@funderburkjim 
corrected snp05.py and snp05.txt

**Comment by funderburkjim** [comment]
@beenooyadav  
  This looks fine!

**Comment by funderburkjim** [comment]
@drdhaval2785  Regarding 'python 2 or 3' ?

Because I want to have work be compatible with the setup of the Cologne server,  I have been working exclusively with Python 2.  

If this compatibility were not an issue, I would probably be working with Python 3, since that
is what the Python Software Foundation is urging;  one reason is that Unicode support is allegedly better
integrated into Python 3.
